#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Daniel's configs here
#make control s freeze the terminal
stty start undef stop undef
alias aa='cd /home/daniel/appacademy'
alias y='yaourt'
alias yu='yaourt -Syu --aur'
alias cleanupzip="find . -name '*.DS_Store' -type f -delete && rm -rf __MACOSX"
alias pacclean="sudo pacman -Rns $(pacman -Qtdq)"
alias be="bundle exec"
alias vim="nvim"

alias attachscreen='xrandr --output LVDS1 --auto --output HDMI1 --auto --left-of LVDS1'
alias detachscreen='xrandr --output HDMI1 --off'

export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
eval "$(rbenv init - )"
NVM_DIR=$HOME/.nvm
source $NVM_DIR/nvm.sh

#vim mode!
export KEYTIMEOUT=1

bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

# if we have a glob this will expand it
setopt GLOB_COMPLETE

# 10 second wait if you do something that will delete everything
setopt RM_STAR_WAIT

export EDITOR=vim

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# I don't know why I never set this before.
setopt EXTENDED_GLOB


zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
