#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Daniel's configs here
alias aa='cd /home/daniel/appacademy'
alias y='yaourt'
alias yu='yaourt -Syu --aur'

export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
eval "$(rbenv init - )"
NVM_DIR=$HOME/.nvm
source $NVM_DIR/nvm.sh


# if we have a glob this will expand it
setopt GLOB_COMPLETE

# 10 second wait if you do something that will delete everything
setopt RM_STAR_WAIT

export EDITOR=vim

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# I don't know why I never set this before.
setopt EXTENDED_GLOB


zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
