#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Daniel's configs here
#make control s freeze the terminal
stty start undef stop undef
alias aa='cd /home/daniel/appacademy'
alias yu='pacaur -Syu'
alias cleanupzip="find . -name '*.DS_Store' -type f -delete && rm -rf __MACOSX"
alias pacclean="sudo pacman -Rns $(pacman -Qtdq)"
alias be="bundle exec"
alias vim="nvim"
alias key="setxkbmap -option caps:escape"
alias weather='curl wttr.in'

alias attachscreen='xrandr --output eDP1 --auto --output DP1 --auto --left-of eDP1 -r 60'
alias attachscreenhdmi='xrandr --output eDP1 --auto --output HDMI2 --auto --left-of eDP1 -r 60'
alias attachscreenrotated='xrandr --output eDP1 --auto --output DP1 --auto --left-of eDP1 --rotate left'
alias detachscreen='xrandr --output DP1 --off'
alias detachscreenhdmi='xrandr --output HDMI2 --off'
alias gbr='for branch in `git branch -r | grep -v HEAD`;do echo -e `git show --format="%ci %cr" $branch | head -n 1` \\t$branch; done | sort'

export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
export PATH="/home/daniel/.local/bin:$PATH"
eval "$(rbenv init - )"
eval "$(thefuck --alias)"
# NVM_DIR=$HOME/.nvm
# source $NVM_DIR/nvm.sh

#vim mode!
export KEYTIMEOUT=1

bindkey -v
bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

# if we have a glob this will expand it
setopt GLOB_COMPLETE

# 10 second wait if you do something that will delete everything
setopt RM_STAR_WAIT

export EDITOR=vim

# Case insensitive globbing
setopt NO_CASE_GLOB

# Be Reasonable!
setopt NUMERIC_GLOB_SORT

# I don't know why I never set this before.
setopt EXTENDED_GLOB

BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"


zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache
source /usr/share/nvm/init-nvm.sh
